Automation.BotTv.UI.Web/Controllers/Campo/CampoAcaoController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Automation.BotTv.Model;
using Automation.BotTv.Repository;
using Automation.BotTv.UI.Web.Models;

namespace Automation.BotTv.UI.Web.Controllers
{
    [Authorize(Roles = "Admin, Comum")]
    public class CampoAcaoController : Controller
    {
        #region Repositorios
        private readonly CampoAcaoREP _repositorioCampoAcao;
        #endregion

        #region Contrutores
        public CampoAcaoController(CampoAcaoREP repositorioCampoAcao)
        {
            _repositorioCampoAcao = repositorioCampoAcao;
        }
        #endregion

        #region Parametros
        private const int _take = 15;
        private int _numeroPagina = 1;
        private int _pagina;
        #endregion

        #region Metodos

        #region Index
        public async Task<IActionResult> Index(int? pagina, string? filtro, string? snAtivo)
        {
            CarregarSimNao(snAtivo);
            int numeroPagina = pagina ?? 1;

            var resultado = await _repositorioCampoAcao.BuscarPaginado(numeroPagina, _take, filtro, snAtivo);

            var viewMOD = new CampoAcaoViewMOD
            {
                ListaCampoAcao = resultado.Dados,
                QtdTotalDeRegistros = resultado.Paginacao.TotalItens,
                PaginaAtual = resultado.Paginacao.PaginaAtual,
                TotalPaginas = resultado.Paginacao.TotalPaginas
            };

            ViewBag.Filtro = filtro;
            ViewBag.SnAtivo = snAtivo;
            ViewBag.Titulo = "Ação do Campo";
            return View("Index", viewMOD);
        }
        #endregion

        #region Cadastrar
        public IActionResult Cadastrar()
        {
            CampoAcaoMOD campoAcaoMOD = new CampoAcaoMOD();

            var viewMOD = campoAcaoMOD.Adapt<CampoAcaoViewMOD>();
            return View(viewMOD);
        }

        [HttpPost]
        public IActionResult Cadastrar(CampoAcaoViewMOD dadosTela)
        {
            var campoAcaoMOD = dadosTela.Adapt<CampoAcaoMOD>();
            campoAcaoMOD.NoAcao = dadosTela.NoAcao;
            campoAcaoMOD.TxObservacao = dadosTela.TxObservacao;
            campoAcaoMOD.SnAtivo = "S";
            campoAcaoMOD.CdUsuarioCadastrou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoAcaoMOD.DtCadastro = DateTime.Now;

            var cadastrou = _repositorioCampoAcao.Cadastrar(campoAcaoMOD);

            if (cadastrou)
            {
                TempData["Modal-Sucesso"] = "Ação do Campo cadastrado com sucesso!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Modal-Erro"] = "Erro ao cadastrar Ação do Campo!";
                return View(dadosTela);
            }
        }
        #endregion

        #region Editar
        public async Task<IActionResult> Editar(int cdAcao)
        {
            var campoAcaoMOD = await _repositorioCampoAcao.BuscarPorCodigo(cdAcao);
            if (campoAcaoMOD == null)
            {
                TempData["Modal-Erro"] = "Ação do Campo não encontrado!";
                return RedirectToAction("Index");
            }
            var viewMOD = campoAcaoMOD.Adapt<CampoAcaoViewMOD>();
            return View(viewMOD);
        }

        [HttpPost]
        public IActionResult Editar(CampoAcaoViewMOD dadosTela)
        {
            var campoAcaoMOD = dadosTela.Adapt<CampoAcaoMOD>();
            campoAcaoMOD.NoAcao = dadosTela.NoAcao;
            campoAcaoMOD.TxObservacao = dadosTela.TxObservacao;
            campoAcaoMOD.CdUsuarioAlterou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoAcaoMOD.DtAlteracao = DateTime.Now;
            campoAcaoMOD.CdAcao = dadosTela.CdAcao;

            var editou = _repositorioCampoAcao.Editar(campoAcaoMOD);

            if (editou)
            {
                TempData["Modal-Sucesso"] = "Ação do Campo alterado com sucesso!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Modal-Erro"] = "Erro ao alterar Ação do Campo!";
                return View(dadosTela);
            }
        }
        #endregion

        #region AlterarStatus
        [HttpPost]
        public async Task<IActionResult> AlterarStatus(int cdAcao)
        {
            var campoAcaoMOD = await _repositorioCampoAcao.BuscarPorCodigo(cdAcao);
            if (campoAcaoMOD == null)
            {
                TempData["Modal-Erro"] = "Ação do Campo não encontrado!";
                return RedirectToAction("Index");
            }

            campoAcaoMOD.SnAtivo = campoAcaoMOD.SnAtivo == "S" ? "N" : "S";
            campoAcaoMOD.CdUsuarioAlterou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoAcaoMOD.DtAlteracao = DateTime.Now;

            var alterouStatus = _repositorioCampoAcao.AlterarStatus(campoAcaoMOD);

            if (alterouStatus)
                TempData["Modal-Sucesso"] = $"Ação do Campo {(campoAcaoMOD.SnAtivo == "S" ? "ativado" : "desativado")} com sucesso!";
            else
                TempData["Modal-Erro"] = "Erro ao alterar status do Ação do Campo. Tente novamente.";

            return RedirectToAction("Index");
        }
        #endregion

        #region Auxiliar

        #region CarregarSimNao
        public void CarregarSimNao(string? snAtivo)
        {
            var lista = new[]
            {
                new SelectListItem{Value = "S", Text = "Ativo"},
                new SelectListItem {Value = "N", Text = "Inativo"}
            };
            ViewBag.ListaSimNao = new SelectList(lista, "Value", "Text", snAtivo);
        }

        #endregion

        #endregion

        #endregion

    }
}

Automation.BotTv.UI.Web/Controllers/Campo/CampoTipoController.cs
using Mapster;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Automation.BotTv.Model;
using Automation.BotTv.Repository;
using Automation.BotTv.UI.Web.Models;

namespace Automation.BotTv.UI.Web.Controllers
{
    [Authorize(Roles = "Admin, Comum")]
    public class CampoTipoController : Controller
    {
        #region Repositorios
        private readonly CampoTipoREP _repositorioCampoTipo;
        #endregion

        #region Contrutores
        public CampoTipoController(CampoTipoREP repositorioCampoTipo)
        {
            _repositorioCampoTipo = repositorioCampoTipo;
        }
        #endregion

        #region Parametros
        private const int _take = 15;
        private int _numeroPagina = 1;
        private int _pagina;
        #endregion

        #region Metodos

        #region Index
        public async Task<IActionResult> Index(int? pagina, string? filtro, string? snAtivo)
        {
            CarregarSimNao(snAtivo);
            int numeroPagina = pagina ?? 1;

            var resultado = await _repositorioCampoTipo.BuscarPaginado(numeroPagina, _take, filtro, snAtivo);

            var viewMOD = new CampoTipoViewMOD
            {
                ListaCampoTipo = resultado.Dados,
                QtdTotalDeRegistros = resultado.Paginacao.TotalItens,
                PaginaAtual = resultado.Paginacao.PaginaAtual,
                TotalPaginas = resultado.Paginacao.TotalPaginas
            };

            ViewBag.Filtro = filtro;
            ViewBag.SnAtivo = snAtivo;
            ViewBag.Titulo = "Tipo de Campo";
            return View("Index", viewMOD);
        }
        #endregion

        #region Cadastrar
        public IActionResult Cadastrar()
        {
            CampoTipoMOD campoTipoMOD = new CampoTipoMOD();

            var viewMOD = campoTipoMOD.Adapt<CampoTipoViewMOD>();
            return View(viewMOD);
        }

        [HttpPost]
        public IActionResult Cadastrar(CampoTipoViewMOD dadosTela)
        {
            var campoTipoMOD = dadosTela.Adapt<CampoTipoMOD>();
            campoTipoMOD.NoCampoTipo = dadosTela.NoCampoTipo;
            campoTipoMOD.TxObservacao = dadosTela.TxObservacao;
            campoTipoMOD.SnAtivo = "S";
            campoTipoMOD.CdUsuarioCadastrou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoTipoMOD.DtCadastro = DateTime.Now;

            var cadastrou = _repositorioCampoTipo.Cadastrar(campoTipoMOD);

            if (cadastrou)
            {
                TempData["Modal-Sucesso"] = "Tipo de Campo cadastrado com sucesso!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Modal-Erro"] = "Erro ao cadastrar Tipo de Campo!";
                return View(dadosTela);
            }
        }
        #endregion

        #region Editar
        public async Task<IActionResult> Editar(int cdCampoTipo)
        {
            var campoTipoMOD = await _repositorioCampoTipo.BuscarPorCodigo(cdCampoTipo);
            if (campoTipoMOD == null)
            {
                TempData["Modal-Erro"] = "Tipo de Campo não encontrado!";
                return RedirectToAction("Index");
            }
            var viewMOD = campoTipoMOD.Adapt<CampoTipoViewMOD>();
            return View(viewMOD);
        }

        [HttpPost]
        public IActionResult Editar(CampoTipoViewMOD dadosTela)
        {
            var campoTipoMOD = dadosTela.Adapt<CampoTipoMOD>();
            campoTipoMOD.NoCampoTipo = dadosTela.NoCampoTipo;
            campoTipoMOD.TxObservacao = dadosTela.TxObservacao;
            campoTipoMOD.CdUsuarioAlterou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoTipoMOD.DtAlteracao = DateTime.Now;
            campoTipoMOD.CdCampoTipo = dadosTela.CdCampoTipo;

            var editou = _repositorioCampoTipo.Editar(campoTipoMOD);

            if (editou)
            {
                TempData["Modal-Sucesso"] = "Tipo de Campo alterado com sucesso!";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["Modal-Erro"] = "Erro ao alterar Tipo de Campo!";
                return View(dadosTela);
            }
        }
        #endregion

        #region AlterarStatus
        [HttpPost]
        public async Task<IActionResult> AlterarStatus(int cdCampoTipo)
        {
            var campoTipoMOD = await _repositorioCampoTipo.BuscarPorCodigo(cdCampoTipo);
            if (campoTipoMOD == null)
            {
                TempData["Modal-Erro"] = "Tipo de Campo não encontrado!";
                return RedirectToAction("Index");
            }

            campoTipoMOD.SnAtivo = campoTipoMOD.SnAtivo == "S" ? "N" : "S";
            campoTipoMOD.CdUsuarioAlterou = Convert.ToInt32(User.Claims.FirstOrDefault(c => c.Type.Contains("CdUsuario"))?.Value);
            campoTipoMOD.DtAlteracao = DateTime.Now;

            var alterouStatus = _repositorioCampoTipo.AlterarStatus(campoTipoMOD);

            if (alterouStatus)
                TempData["Modal-Sucesso"] = $"Tipo de Campo {(campoTipoMOD.SnAtivo == "S" ? "ativado" : "desativado")} com sucesso!";
            else
                TempData["Modal-Erro"] = "Erro ao alterar status do Tipo de Campo. Tente novamente.";

            return RedirectToAction("Index");
        }
        #endregion

        #region Auxiliar

        #region CarregarSimNao
        public void CarregarSimNao(string? snAtivo)
        {
            var lista = new[]
            {
                new SelectListItem{Value = "S", Text = "Ativo"},
                new SelectListItem {Value = "N", Text = "Inativo"}
            };
            ViewBag.ListaSimNao = new SelectList(lista, "Value", "Text", snAtivo);
        }

        #endregion

        #endregion

        #endregion

    }
}

Automation.BotTv.UI.Web/Controllers/Common/LoginController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Claims;
using Automation.BotTv.Data;
using Automation.BotTv.Model;
using Automation.BotTv.Repository;
using Automation.BotTv.UI.Web.Models;

namespace Automation.BotTv.UI.Web.Controllers
{
    [AllowAnonymous]
    public class LoginController : Controller
    {
        #region Repositorios
        private readonly LoginREP _repositorioLogin;
        private readonly UsuarioREP _repositorioUsuario;
        private readonly SistemaREP _repositorioSistema;
        private readonly AcessaDados _acessaDados;
        private readonly IConfiguration _configuration;
        #endregion

        #region Construtor
        public LoginController(LoginREP loginService, UsuarioREP usuarioService, SistemaREP sistemaService, IConfiguration configuration, AcessaDados acessaDados)
        {
            _repositorioLogin = loginService;
            _repositorioUsuario = usuarioService;
            _repositorioSistema = sistemaService;
            _configuration = configuration;
            _acessaDados = acessaDados;
        }
        #endregion

        #region EfeturarLogin
        [AllowAnonymous]
        public async Task<IActionResult> EfetuarLogin()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> EfetuarLogin(LoginViewMOD model, string? returnUrl)
        {

            UsuarioMOD usuario = new UsuarioMOD();

            usuario.TxLogin = model.Login.ToUpper();
            usuario.TxSenha = model.Password;

            bool valido = await _repositorioLogin.ValidarLogin(usuario);

            if (valido)
            {
                usuario = await _repositorioLogin.BuscarPorLogin(usuario);
                var id = _configuration.GetSection("CodigoSistema").Value;


                if (!string.IsNullOrEmpty(usuario.NrCpf))
                {
                    usuario = await _repositorioLogin.BuscarPorCpf(usuario);
                    SistemaMOD sistema = await _repositorioSistema.BuscarPorCodigo(Convert.ToInt32(id));
                    UsuarioSistemaMOD usuarioSistema = await _repositorioUsuario.BuscarAcessoUsuarioSistema(usuario.CdUsuario, sistema.CdSistema);
                    string tpNivelAcesso = _repositorioLogin.ObterTpNivelAcessoUsuario(usuario.CdUsuario);

                    if (usuario.CdUsuario > 0 && usuarioSistema.Usuario.CdUsuario > 0)
                    {
                        string role = tpNivelAcesso == "A" ? "Admin" : "Comum";

                        var claims = new List<Claim>
                            {
                                new Claim(ClaimTypes.Name, usuario.TxLogin),
                                new Claim("NrCpf", usuario.NrCpf),
                                new Claim("CdUsuario", usuario.CdUsuario.ToString()),
                                new Claim("NmUsuario", usuario.NmUsuario.ToString()),
                                new Claim("Avatar", usuario.Avatar.TxLocalFoto),
                                new Claim(ClaimTypes.Role, role),
                            };

                        var claimsIdentity = new ClaimsIdentity(
                            claims, CookieAuthenticationDefaults.AuthenticationScheme);

                        var authProperties = new AuthenticationProperties
                        {
                            AllowRefresh = true,
                            IsPersistent = true,
                            IssuedUtc = DateTime.Now,
                        };

                        await HttpContext.SignInAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity),
                            authProperties);

                        if (!string.IsNullOrEmpty(returnUrl))
                            return Redirect(returnUrl);
                        else
                            return RedirectToAction("Index", "Home");
                    }
                }
            }
            ModelState.AddModelError<LoginViewMOD>(x => x.Login, "Usuário e/ou Senha Inválidos.");
            return View(model);
        }
        #endregion

        #region Sair
        public async Task<ActionResult> Sair(string? returnUrl = null)
        {
            var CdUsuario = Convert.ToInt32(User.Claims.FirstOrDefault(x => x.Type == "CdUsuario").Value);

            await HttpContext.SignOutAsync(
                            CookieAuthenticationDefaults.AuthenticationScheme, new AuthenticationProperties { RedirectUri = "/Login/EfetuarLogin" });

            return RedirectToAction("EfetuarLogin");
        }
        #endregion
    }
}

Automation.BotTv.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Bot TV</title>
    <partial name="_PartialStyles" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/admin-lte/plugins/jquery/jquery.min.js"></script>
</head>
<body class="layout-fixed sidebar-expand-lg sidebar-mini bg-body app-loaded sidebar-collapse" data-bs-theme="light">
    <partial name="_PartialToast" />
    <div class="app-wrapper">
        @*loader para exibir enquanto carrega algum conteúdo*@ 
        <div class="loader" style="display: none;">
            <span class="fa fa-spinner fa-pulse fa-3x fa-fw text-primary"></span>
        </div>
        <partial name="_PartialMenuTop" />
        <partial name="_PartialMeusAcessos" />
        <main class="app-main bg-light-gray">
            <div class="app-content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-6">
                            <hgroup>
                                <h1> @ViewBag.MainTitle</h1>
                                <h6 class="text-gray-dark">@ViewBag.SubTitle</h6>
                            </hgroup>
                        </div>
                    </div>
                </div>
            </div>
            <div class="app-content">
                <div class="container-fluid">
                    <partial name="_PartialMensagem" />
                    @RenderBody()
                </div>
            </div>
            <div class="top-page" id="scrollTop" style="display: none;">
                <span class="fas fa-arrow-up text-dark opacity-50" data-toggle="tooltip" data-placement="left"></span>
            </div>
        </main>
        <partial name="_PartialFooter" />
    </div>
    <partial name="_PartialScripts" />
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Automation.BotTv.UI.Web/Views/Shared/_PartialFooter.cshtml
@* RODAPE DA PAGINA *@
<footer class="app-footer text-end">
    <span> &copy; @DateTime.Now.Year Vinicius Santiago.</span>
</footer>

Automation.BotTv.UI.Web/Views/Shared/_PartialMenuTop.cshtml
@{
    var nomeCompleto = User.FindFirst("NmUsuario")?.Value ?? "";
    var nomes = nomeCompleto.Split(' ', StringSplitOptions.RemoveEmptyEntries);

    string primeiroNome = nomes.Length > 0 ? nomes[0] : "";
    string ultimoNome = nomes.Length > 1 ? nomes[nomes.Length - 1] : "";

    string formatarNome(string nome) =>
        char.ToUpper(nome[0]) + nome.Substring(1).ToLower();

    var nomeFormatado = $"{formatarNome(primeiroNome)} {formatarNome(ultimoNome)}";
}

<nav class="app-header navbar navbar-expand bg-gray-light shadow">
    <div class="container-fluid">
        <ul class="navbar-nav">
            <li class="nav-item"> <a class="nav-link" data-lte-toggle="sidebar" href="#" role="button"> <i class="fa fa-bars text-gray-dark"></i> </a> </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item user-menu me-2 mt-1">
                <img src="@Configuration.GetSection("UrlRepositorio").Value/@User.FindFirst("Avatar").Value" class="user-image rounded-circle shadow bg-white" alt="User Image">
                <span class="d-none d-md-inline text-gray-dark me-4" style="font-size: 1.1em;">@nomeFormatado</span>
            </li>
            <li class="nav-item user-menu me-3">
                <a asp-controller="Login" asp-action="Sair" type="button" class="btn bg-red shadow text-white py-1 px-2 fw-light">
                    sair<i class="ms-2 fas fa-arrow-alt-circle-right"></i>
                </a>
            </li>
        </ul>
    </div>
</nav>

Automation.BotTv.UI.Web/Views/Shared/_PartialMeusAcessos.cshtml
<aside class="app-sidebar bg-gray-light shadow">
    <div class="sidebar-brand">
        <a href="#" class="brand-link">
            <img src="logo.png" alt="Logo" class="brand-image" style="opacity: .8">
        </a>
    </div>
    <div class="sidebar-wrapper overflow-hidden">
        <div>
            <nav class="mt-1">
                <ul class="nav sidebar-menu flex-column" data-lte-toggle="treeview" role="menu" data-accordion="false">
                    <li class="nav-item mt-2">
                        <div href="#" class="nav-item">
                            <a href="@Url.Action("Index", "Home")" class="nav-link">
                                <i class="nav-icon fas fa-chart-line text-gray-dark"></i>
                                <p class="text-gray-dark">Automação</p>
                            </a>
                        </div>
                    </li>
                    <hr />
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-columns text-gray-dark"></i>
                            <p class="text-gray-dark">
                                Painéis
                                <i class="nav-arrow bi bi-chevron-right text-gray-dark"></i>
                                <i class="nav-arrow fa fa-chevron-right text-gray-dark"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Painel")" class="nav-link">
                                    <i class="nav-icon fas fa-columns text-white"></i>
                                    <p class="text-white">Cadastrados</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "PainelTipo")" class="nav-link">
                                    <i class="nav-icon fas fa-list text-white"></i>
                                    <p class="text-white">Tipos</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-map-pin text-gray-dark"></i>
                            <p class="text-gray-dark">
                                Campos
                                <i class="nav-arrow bi bi-chevron-right text-gray-dark"></i>
                                <i class="nav-arrow fa fa-chevron-right text-gray-dark"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "CampoAcao")" class="nav-link">
                                    <i class="nav-icon fas fa-hand-point-up text-white"></i>
                                    <p class="text-white">Ações</p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "CampoTipo")" class="nav-link">
                                    <i class="nav-icon fas fa-list text-white"></i>
                                    <p class="text-white">Tipos</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link">
                            <i class="nav-icon fas fa-desktop text-gray-dark"></i>
                            <p class="text-gray-dark">
                                Maquinas
                                <i class="nav-arrow bi bi-chevron-right text-gray-dark"></i>
                                <i class="nav-arrow fa fa-chevron-right text-gray-dark"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            <li class="nav-item">
                                <a href="@Url.Action("Index", "Maquina")" class="nav-link">
                                    <i class="nav-icon fas fa-desktop text-white"></i>
                                    <p class="text-white">Cadastradas</p>
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
</aside> 

Automation.BotTv.UI.Web/Views/Shared/_PartialStyles.cshtml
@* BOOTSTRAP *@
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-grid.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-reboot.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-utilities.css" />
<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />

@* ADMINLTE *@
<link href="~/lib/admin-lte/dist/css/alt/adminlte.components.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/alt/adminlte.core.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/alt/adminlte.extra-components.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/alt/adminlte.light.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/alt/adminlte.pages.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/alt/adminlte.plugins.css" rel="stylesheet" />
<link href="~/lib/admin-lte/dist/css/adminlte.css" rel="stylesheet" />


@* PLUGIN *@
<link href="~/lib/admin-lte/plugins/fontawesome-free/css/all.min.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/select2/css/select2.min.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/toastr/toastr.min.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/daterangepicker/daterangepicker.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/bootstrap-switch/css/bootstrap3/bootstrap-switch.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/fullcalendar/main.min.css" rel="stylesheet" />
<link href="~/lib/admin-lte/plugins/bs-stepper/css/bs-stepper.min.css" rel="stylesheet" />

@*FILE INPUT*@
<link href="~/lib/bootstrap-fileinput/css/fileinput.css" rel="stylesheet" />

@*ICHECK BOOTSTRAP*@
<link href="~/lib/admin-lte/plugins/icheck-bootstrap/icheck-bootstrap.min.css" rel="stylesheet" />

@*TOASTR*@
<link href="~/lib/admin-lte/plugins/toastr/toastr.min.css" rel="stylesheet" />

@* RANGE *@
<link href="~/lib/admin-lte/plugins/ion-rangeslider/css/ion.rangeslider.min.css" rel="stylesheet" />

@* TOUR *@
<link href="~/lib/bootstrap-tour/css/bs5-intro-tour.css" rel="stylesheet" />

@* JQUERY UI *@
<link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">

@* SITE *@
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
<link href="~/css/animate.min.css" rel="stylesheet" />
<link href="~/css/custom.css" rel="stylesheet" />